import {
  CircleCheckIcon,
  InfoIcon,
  Loader2Icon,
  OctagonXIcon,
  TriangleAlertIcon,
} from 'lucide-react'
import { Toaster as Sonner, type ToasterProps } from 'sonner'

import { resolveTheme, useUiStore } from '@/stores/ui-store'

/**
 * Generated by the shadcn CLI, then rewritten to read the local theme store.
 *
 * The generated version imports `next-themes`, which is a Next.js package and
 * has no business in a Vite application; `useUiStore` already holds the
 * preference this needs.
 */
const Toaster = ({ ...props }: ToasterProps) => {
  const theme = useUiStore((state) => state.theme)

  return (
    <Sonner
      theme={theme === 'system' ? resolveTheme(theme) : theme}
      className="toaster group"
      icons={{
        success: <CircleCheckIcon className="size-4" />,
        info: <InfoIcon className="size-4" />,
        warning: <TriangleAlertIcon className="size-4" />,
        error: <OctagonXIcon className="size-4" />,
        loading: <Loader2Icon className="size-4 animate-spin" />,
      }}
      style={
        {
          '--normal-bg': 'var(--popover)',
          '--normal-text': 'var(--popover-foreground)',
          '--normal-border': 'var(--border)',
          '--border-radius': 'var(--radius)',
        } as React.CSSProperties
      }
      toastOptions={{ classNames: { toast: 'cn-toast' } }}
      {...props}
    />
  )
}

export { Toaster }
