package com.company.taskmanagementplatform.reports;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.company.taskmanagementplatform.reports.dto.TrendPointResponse;
import com.company.taskmanagementplatform.tasks.TaskTrendPoint;

/**
 * Turns two sparse series into one dense one.
 *
 * <p>The database returns a row only for a bucket that had something in it, which is the right thing
 * for it to do and the wrong thing for a chart to receive. A week with no completions is a real fact
 * about that week; leaving it out makes the line jump straight from the week before to the week
 * after and invites a client to invent the shape between them.
 *
 * <p>So every bucket from the start of the window to its end is present, in order, and the two series
 * are merged onto the same axis. A quiet fortnight draws a flat line at zero.
 *
 * <p>The buckets are generated by walking {@link TrendGranularity#next}, the same code that decides
 * which bucket a given day belongs to, rather than by dividing the window into equal parts. Months
 * are not equal parts, and weeks are only equal if the window happens to begin on a Monday.
 */
final class TrendBuckets {

    private TrendBuckets() {}

    /**
     * Every bucket of the window, carrying whatever the two series had in it.
     *
     * <p>The first bucket is the one containing the first day of the window, so a window starting on
     * a Wednesday with weekly buckets opens on the Monday before it, which is the bucket the database
     * grouped that Wednesday into. Reporting a partial first week under its own Monday is honest; a
     * week labelled Wednesday would not line up with any other chart in the product.
     */
    static List<TrendPointResponse> merge(
            ReportPeriod period,
            TrendGranularity granularity,
            List<TaskTrendPoint> created,
            List<TaskTrendPoint> completed) {

        Map<LocalDate, Long> createdByBucket = index(created);
        Map<LocalDate, Long> completedByBucket = index(completed);

        List<TrendPointResponse> points = new ArrayList<>();
        LocalDate bucket = granularity.startOfBucket(period.from());
        LocalDate last = granularity.startOfBucket(period.to());

        while (!bucket.isAfter(last)) {
            points.add(new TrendPointResponse(
                    bucket,
                    createdByBucket.getOrDefault(bucket, 0L),
                    completedByBucket.getOrDefault(bucket, 0L)));
            bucket = granularity.next(bucket);
        }

        return List.copyOf(points);
    }

    private static Map<LocalDate, Long> index(List<TaskTrendPoint> points) {
        Map<LocalDate, Long> byBucket = new HashMap<>();
        for (TaskTrendPoint point : points) {
            byBucket.merge(point.bucketStart(), point.count(), Long::sum);
        }
        return byBucket;
    }
}
