package com.company.taskmanagementplatform.attachments;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.Duration;
import java.util.Optional;

/**
 * A {@link FileStore} that writes under a directory on this machine.
 *
 * <p>For development and for the test suite, which is why the suite needs nothing but Docker and
 * PostgreSQL to exercise uploads end to end. The requirements say files must not be stored on the
 * application server in production, and {@code StorageConfig} refuses to start there with this store
 * wired, so this class cannot become the production answer by accident.
 *
 * <p>It issues no presigned URLs, so downloads stream through the application. That is the case the
 * download endpoint has to handle anyway, and having the default implementation exercise it means
 * the path is tested rather than theoretical.
 */
class LocalFileStore implements FileStore {

    private final Path root;

    LocalFileStore(Path root) {
        this.root = root.toAbsolutePath().normalize();
    }

    @Override
    public String provider() {
        return StorageProperties.Provider.LOCAL.name();
    }

    @Override
    public void put(String key, InputStream content, String contentType, long sizeBytes) {
        Path target = resolve(key);
        try {
            Files.createDirectories(target.getParent());
            Files.copy(content, target, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            throw new UncheckedIOException("Could not store " + key, e);
        }
    }

    @Override
    public InputStream open(String key) {
        try {
            return Files.newInputStream(resolve(key));
        } catch (IOException e) {
            throw new UncheckedIOException("Could not read " + key, e);
        }
    }

    /**
     * Removes the file, and raises rather than swallows a failure.
     *
     * <p>This used to log and return, on the reasoning that reclaiming space is housekeeping and should
     * not fail a request. That reasoning held while nothing called it. The purge is the caller now, and
     * it deletes the database row only once this has returned: a swallowed failure here would mean the
     * row went and the file stayed, leaving bytes on disk that nothing in the schema can name any more.
     *
     * <p>A file that was already absent is a success. {@code deleteIfExists} returns false rather than
     * throwing, and false is the post-condition the caller wanted.
     */
    @Override
    public void delete(String key) {
        try {
            Files.deleteIfExists(resolve(key));
        } catch (IOException e) {
            throw new UncheckedIOException("Could not remove " + key, e);
        }
    }

    /**
     * Always empty: there is no way to sign a path on a local disk, and nothing outside this process
     * could fetch it if there were. Every download from this store therefore streams, which means
     * the streaming branch of the download endpoint is the one the test suite exercises by default.
     */
    @Override
    public Optional<URI> presignedUrl(String key, Duration ttl, String filename, String contentType) {
        return Optional.empty();
    }

    /**
     * Keys are generated by this module and contain nothing a user supplied, so this cannot be
     * reached with a traversal today. It is still checked, because the check costs nothing and the
     * day somebody adds a second caller is the day it would have mattered.
     */
    private Path resolve(String key) {
        Path resolved = root.resolve(key).normalize();
        if (!resolved.startsWith(root)) {
            throw new IllegalArgumentException("Storage key escapes the store root");
        }
        return resolved;
    }
}
